<a href="https://colab.research.google.com/github/plajuan/ML_Study/blob/main/1_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1 • Test scores

Create a series of 10 elements, random integers from 70 to 100, representing scores on a monthly exam. Set the index to be the month names, starting in September and ending in June. (If these months don’t match the school year in your location, feel free to make them more realistic.)

With this series, write code to answer the following questions:

1. What is the student’s average test score for the entire year?
1. What is the student’s average test score during the first half of the year (i.e., the first five months)?
1. What is the student’s average test score during the second half of the year?
1. Did the student improve their performance in the second half? If so, by how much?

In [23]:
from pandas import Series, DataFrame
import pandas as pd
from numpy.random import randn
import numpy as np

In [24]:
#seeds random with 0 to make results the same as the book
g = np.random.default_rng(0)
months = 'Sep Oct Nov Dec Jan Feb Mar Apr May Jun'.split()
s = Series(g.integers(70,101,10), index=months)
s

Sep    96
Oct    89
Nov    85
Dec    78
Jan    79
Feb    71
Mar    72
Apr    70
May    75
Jun    95
dtype: int64

In [25]:
#1. What is the student’s average test score for the entire year?
s.mean()

np.float64(81.0)

In [26]:
#2. What is the student’s average test score during the first half of the year (i.e., the first five months)?
s[:5].mean()

np.float64(85.4)

In [27]:
#3. What is the student’s average test score during the second half of the year?
s[5:].mean()

np.float64(76.6)

In [31]:
#4. Did the student improve their performance in the second half? If so, by how much?
first_half_average = s.loc['Sep':'Jan'].mean()
second_half_average = s.loc['Feb':'Jun'].mean()
diff = second_half_average - first_half_average
print(f'First half average: {first_half_average}')
print(f'Second half average: {second_half_average}')
print(f'Improvement: {"up" if diff > 0 else "down"} {abs(diff):.2f}')

First half average: 85.4
Second half average: 76.6
Improvement: down 8.80

In [34]:
#5. In which month did this student get their highest score?
#Note that there are at least three ways to accomplish this: you can sort the values, taking the largest one, using a boolean (mask) index to find rows that match the value of s.max(),
#the highest value, or invoking s.idxmax(), which returns the index of the highest value.
m1 = s[s.idxmax()]
m2 = s.max()
m3 = s.sort_values(ascending=False).head(1).iloc[0]
if m1 != m2 or m1 != m3:
  raise ValueError('Values must be the same!')
print(f'Highest score: {m3}')

Highest score: 96

In [41]:
#6. What were this student’s five highest scores?
for label, score in enumerate(s.sort_values(ascending=False).head(5)):
  print(f'{label+1}. {score}')
s.sort_values(ascending=False).head(5)

1. 96
2. 95
3. 89
4. 85
5. 79

Sep    96
Jun    95
Oct    89
Nov    85
Jan    79
dtype: int64

In [40]:
#7. Round the student’s scores to the nearest 10. (A score of 82 would be rounded down to 80, but a score of 87 would be rounded up to 90.)
#Be sure to read the documentation for the round method (http://mng.bz/8rzg) to understand its arguments and how it handles numbers like 15 and 75.
df_round = np.round(s/10)*10
df_round

Sep    100.0
Oct     90.0
Nov     80.0
Dec     80.0
Jan     80.0
Feb     70.0
Mar     70.0
Apr     70.0
May     80.0
Jun    100.0
dtype: float64

#Exercise 2 • Scaling test scores
Generate 10 test scores between 40 and 60, again using an index starting with September and ending with June. Find the mean of the scores and add the difference between the mean and 80 to each of the scores.

In [55]:
g = np.random.default_rng(0)
s = Series(g.integers(40,61,10), index=months)
print('Grades mean:', s.mean())
s_diff = s.apply(lambda x: x + (80 - s.mean()))
#s_diff = s + (80 - s.mean())
print('New grades mean:', s_diff.mean())
s_diff

Grades mean: 47.2
New grades mean: 79.99999999999999

Sep    89.8
Oct    85.8
Nov    82.8
Dec    77.8
Jan    78.8
Feb    72.8
Mar    73.8
Apr    72.8
May    75.8
Jun    89.8
dtype: float64